service: ms-auth

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: 'us-east-1'
  memorySize: 512
  stage: ${opt:stage, "${env:stage, 'dev'}"}
  apiGateway:
    restApiId: ${ssm:/destaka/infra/api-gateway/id}
    restApiRootResourceId: ${ssm:/destaka/infra/api-gateway/root-resource-id}

  environment:
    user_pool_id: { Ref: UserPool }
    client_id: { Ref: UserClient }
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
          Resource: "*"


custom:
  serviceName: auth
  contextPath: ${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}
  funcDir: src/framework/functions

functions:
  createUserIdentity:
    handler: ${self:custom.funcDir}/users/createUserIdentity.handler
    events:
      - http:
          path: ${self:custom.baseApi}/sign-in
          method: post
          cors:
            origin: '*'
            headers: '*'

resources:
  - ${file(./devops/resources/ssm.yml)}
  - ${file(./devops/resources/cognito.yml)}
